### ISSUE TITLE
support compilation on Windows and OS X

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/funnel#1]
`make build` fails on OS X.
Consider adding ` -std=c89 -pedantic` to the `gcc` command to improve portability.

**Comment by mwetter** [comment]
@JayHuLBL : Testing on Windows is still pending.

**Comment by devil-d3** [comment]
make build in windows throws an error
make -C src build
make[1]: Entering directory `/c/Users/Dell/Desktop/funnel-issue1_windows/src'
gcc -Wall -Wfloat-equal -fPIC -c  *.c
mkdir_p.c: In function 'mkdir_p':
mkdir_p.c:28:17: warning: implicit declaration of function 'mkdir' [-Wimplicit-function-declaration]
             if (mkdir(_path, S_IRWXU) != 0) {
                 ^~~~~
gcc -Wall -Wfloat-equal -shared -fPIC -Wl,-soname,libfunnel.so -o libfunnel.so algorithmRectangle.o compare.o main.o mkdir_p.o readCSV.o tube.o tubeSize.o -lc
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lc
collect2.exe: error: ld returned 1 exit status
make[1]: *** [build] Error 1
make[1]: Leaving directory `/c/Users/Dell/Desktop/funnel-issue1_windows/src'
make: *** [build] Error 2

**Comment by devil-d3** [comment]
make build  results in error while compiling on Windows using gcc(MinGW)

**gcc -Wall -Wfloat-equal -shared -fPIC -Wl,-soname,libfunnel.so -o libfunnel.so algorithmRectangle.o compare.o main.o mkdir_p.o readCSV.o tube.o tubeSize.o -lc
c:/....../mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lc** 

This is the error i'm getting

**Comment by AntoineGautier** [comment]
@mwetter 
Can I delete the corresponding branch [issue1_windows](https://github.com/lbl-srg/funnel/tree/issue1_windows) since the issue has been closed by last [PR](https://github.com/lbl-srg/funnel/pull/27#issuecomment-459242323)?

**Comment by mwetter** [comment]
Yes, please delete it.
