### ISSUE TITLE
Add test cases and integration testing for different operating systems

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/funnel#24]

**Comment by AntoineGautier** [comment]
@mwetter @JayHuLBL 
I uploaded the first test cases on the branch [issue24_addTestCases](https://github.com/AntoineGautier/funnel/tree/issue24_addTestCases) (see `tests` directory and the `readme.txt` file for information about the tests if needed).
Besides some little corrections to be made, the test `ambiguous2` requires some design consideration about the tool. It shows that `y` tolerance can be largely exceeded without any error being detected because of the `x` tolerance see [plot](https://github.com/AntoineGautier/Data/blob/master/plot_image.svg). I wonder if this kind of algorithm should not be preferred then:

- Interpolate `x` and `y` reference values at `x` test values: provides `y_ref` values.
- Test if `(x_test, y_test)` test points are within the ellipse centered at `(x_test, y_ref)` and with `atolx` and `atoly` as parameters.

I will go on with OS integration testing until I get your opinion on that and conclude numeric testing.

**Comment by AntoineGautier** [comment]
@mwetter @JayHuLBL 
Following our discussion about the algorithm itself:

- We agreed that the L2-norm criterion for testing the `x` and `y` tolerances had nothing to do with the problem isolated in test case `ambiguous2`.
- The problem is fully related to the _continuous_ VS _discrete_ (or _trajectory_ VS _point to point_) comparison logic.
- The alternative principle described above does not handle well time events offsets within `x` tolerance. It was proposed to further add a `y` interpolation of reference points at `y` test values. But after thinking about it, this leads to the same problem as the one in test case `ambiguous2`. At the moment I cannot think of a more robust algorithm than the one already implemented if we want to handle time events offsets.

Concerning OS integration, I ran tests on Windows 10 x64:

- Compilation with `mingw-w64 make` is OK. I still need to run all the numeric tests on the binary: I would like to include them in a `pytest` framework if OK with you.
- I ran into an OS exception while trying to test `pyfunnel`. The call to `cdll.LoadLibrary` yields `WindowsError: [Error 126] Module not found` though `os.path.isfile` returns `True`. My first guess would be a dependencies issue. Does that ring a bell? Should I look further and try to solve this or is it not a priority?

**Comment by mwetter** [comment]
@AntoineGautier : the call to `cdll.LoadLibrary` (at https://github.com/AntoineGautier/funnel/blob/issue24_addTestCases/bin/pyfunnel.py#L22) yields an error because it tries to load a Linux64 bit library. This section need to be changed to detect the operating system, and then load the corresponding dll.
