### ISSUE TITLE
Correct fixed path length

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/funnel#34]
The folder name is fixed in mkdir_p.c:
```
int mkdir_p(const char *path)
{
    /* Adapted from http://stackoverflow.com/a/2336245/119527 */
    const size_t len = strlen(path);
    char _path[PATH_MAX];
    char *p; 
```
Also, `PATH_MAX` is defined as
```
#ifndef PATH_MAX
#define PATH_MAX MAX_PATH
#endif
```
but `MAX_PATH` seems not be defined (and why is another constant needed?).

This code should be changed to dynamically allocate storage.

**Comment by JayHuLBL** [comment]
@mwetter I just talked with Antoine yesterday about some potential issues like that. I will go through the C code again to avoid the recently realized issues.

**Comment by AntoineGautier** [comment]
@JayHuLBL What is the status of this issue?
(We are about to release the newversion of `buildingspy` with `funnel` as the default comparison tool: I am checking the remaining open issues...)
