### ISSUE TITLE
tubeSize.c hard-coded what seems to be a tolerance

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/funnel#4]
`tubeSize.c` contains 
```
	if (maxX != minX) {
		ratio = max(0.0004, ((maxY - minY + abs(minY)) / (maxX - minX)));
	} else {
		ratio = 0;
	}
```
It is not clear what `0.0004` is. Should this scale with the tolerance? Also, `maxX` and `minX` are `double` and hence need to be compared within a tolerance.

**Comment by beutlich** [comment]
Note, that we propsed to change it by https://github.com/modelica-tools/csv-compare/pull/52/commits/9818b339b48c408567a667e7925862591a4c3f3b

**Comment by mwetter** [comment]
@JayHuLBL Please also add the changes from the modelica-tools repository to our implementation.
