### ISSUE TITLE
Test on CentOS

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/funnel#40]
This is to test funnel on CentOS and address this bug [#291](https://github.com/lbl-srg/BuildingsPy/issues/291) in BuildingsPy.

**Comment by AntoineGautier** [comment]
@Mathadon funnel tests run on CentOS. Could you upload the reference `.txt` file and the test `.mat` file (retrieved by setting `cleanup=False` in `regressiontest.Tester`)?

**Comment by AntoineGautier** [comment]
Pushed a fix for testing for a valid path on CentOS.

To do:

- [ ] Include CentOS test in travis.

**Comment by Mathadon** [comment]
@AntoineGautier I was mistaken, the bug happens on Ubuntu 14.04, not on centos.

**Comment by AntoineGautier** [comment]
Closing this issue as it seems stale.
