### ISSUE TITLE
Results precision and formatting

### ISSUE THREAD

**Issue by DeadParrot** [lbl-srg/funnel#53]
The PyFunnel results files use the Python default 6-digit floating point precision and f formatting, which doesn't work well in some cases:
- Signals can have large magnitudes but very small changes such that 6 digits is inadequate to capture changes in the values.
- Signals that match very closely can have very small errors such that all zeros or at least precision loss occurs with f formatting. The use of g or e formatting is needed in these situations.

**Comment by AntoineGautier** [comment]
Thanks.
This comes from https://github.com/lbl-srg/funnel/blob/master/src/compare.c#L108
where `%lf` (equivalent to `%f` when used in `fprintf`) implies that the number of digits after the decimal-point character is equal to the precision specification. If the precision is missing, it is taken as 6.
This should be replaced by `%g`.
A correction of https://github.com/lbl-srg/funnel/blob/master/src/readCSV.c#L86 may also be required.
