### ISSUE TITLE
Better documentation and error handling on two-column CSV file limitation

### ISSUE THREAD

**Issue by beutlich** [lbl-srg/funnel#76]
It's hardly visible from the documentation that funnel only operates on two-column CSV files. Furthermore, nothing is logged to c_funnel.log if multi-column CSV files are passed to funnel. In my case I wondered about the unexpected output CSV files with only one row.

1. It should be maded transparent (in README and help text) that only two-column CSV files are handled.
2. The error reporting should be improved for multi-column CSV files.
3. Are there any plans to support multi-column CSV files?

Thank you!

**Comment by JayHuLBL** [comment]
@beutlich
Thanks for the suggestions. We will improve the documentation and the error reporting.

For your third item, we currently don't have a plan to support the multi-column CSV files. Would you please share with us the scenarios that need to use multi-column file?

**Comment by beutlich** [comment]
@JayHuLBL Thanky for the fast reply.

> Would you please share with us the scenarios that need to use multi-column file?

There have bee some very early ideas within the MA Project Libraries to utilize funnel as a stand-alone tool for result comparison substituting csv-compare. One valid reason might be that csv-compare is rather unmaintained.

Hence, I tried to evaluate funnel and noticed that it cannot substitute csv-compare in its current state due to this limitations with the multi-colum CSV.

One other idea I have is to back-port the core compare algorithms using absolute and local tolerances also to csv-compare such that both tools share the same comparisons. What do you think?

@FYI @GallLeo

**Comment by mwetter** [comment]
@beutlich If supporting multi-column CSV files prevents wider use of funnel, we should scope what it is needed to support this. I would think that should be a small lift.

**Comment by beutlich** [comment]
@mwetter I do not know the exact requirements of MA Project Libraries for a csv-compare substitute. So for now I'd say it is useful to improve documentation and error logging of funnel.
