### ISSUE TITLE
Update pypi version to 1.0.0?

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/funnel#81]
The latest version on pypi is [0.3.0](https://pypi.org/project/pyfunnel/#description).  Any interest in adding 1.0.0 to pypi?

**Comment by mwetter** [comment]
@AntoineGautier : Could you please push version 1.0.0 to pypi.

**Comment by AntoineGautier** [comment]
Thanks for the reminder!
I have now published v1.0.0 as well as the new release v1.0.1 that fixes a dependency issue on Ubuntu 20.04: https://pypi.org/project/pyfunnel/

**Comment by dhblum** [comment]
That's great thank you!
